AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb

Style/Documentation:
  Exclude:
    - app/helpers/application_helper.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - config/application.rb
    - test/**/*
