default: &default
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ideal_rails_app_development

test:
  <<: *default
  database: ideal_rails_app_test

production:
  <<: *default
  database: ideal_rails_app_production
